name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme SwiftPlantUMLApp -sdk macosx clean build